version: '3'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    command: "npm run dev"
    networks:
      - postgres

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${DB_USER:-admin}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-admin}
      PGDATA: /data/postgres
    volumes:
      - ./.docker/postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
